import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import "@aptos-labs/wallet-adapter-ant-design/dist/index.css";
import { AptosWalletAdapterProvider } from "@aptos-labs/wallet-adapter-react";
import { ThemeConfig } from 'antd';
import { PetraWallet } from "petra-plugin-wallet-adapter";
import { WalletSelector } from "@aptos-labs/wallet-adapter-ant-design";
import Creature from "./Creature";

const inter = Inter({ subsets: ["latin"] });

const wallets = [
  new PetraWallet()
]

const antThemeConfig: ThemeConfig = {
}

export default function Home() {
  return (<AptosWalletAdapterProvider plugins={wallets} autoConnect={true}>
    <App />
  </AptosWalletAdapterProvider>);
};

function itoa(i: number) {
  return String.fromCharCode(i + 'a'.charCodeAt(0));
}

function App() {
  const [gene, setGene] = useState("abc");

  function randomize() {
    let randomChar = () => itoa(Math.floor(Math.random() * 3));
    setGene(`${randomChar()}${randomChar()}${randomChar()}`);
    console.log(`randomized gene: ${gene}`);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <WalletSelector />
        <button onClick={randomize}>Randomize</button>
        <Creature gene={gene}/>
      </main>
    </>
  );
}
